#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    #Enable autocomplete layer
    #
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 2
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    guifont = "Hack Nerd Font Mono Regular:h15"
    fontligatures = true
    editor_fontLigatures= true
    enable_guicolors = true
    word_wrap = true

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "format"
enable = true

[[layers]]
  name = "git"

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

[[layers]]
  name = "github"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30


[[custom_plugins]]
repo = "lilydjwg/colorizer"
merged = false

[[layers]]
name = "lang#python"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true
  buffer_index_type = 2


[[layers]]
  name = "lang#javascript"

[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true

[[layers]]
name = 'lang#javascript'
format_on_save = true

[[layers]]
  name = "lang#java"

[[layers]]
  name = 'lang#java'
  format_on_save = true

[[layers]]
  name = "denite"

[[layers]]
  name = "lang#batch"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#html"
  user_emmet_leader_key = "<C-e>"

[[layers]]
  name = "tools"

[[layers]]
  name = "shell"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#matlab"

  [[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#latex"

 [[layers]]
  name = "lang#perl"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#rust"
  
[[layers]]
  name = "lang#toml"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "tools"  

[[layers]]
  name = "tmux"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = "lang#WebAssembly"

[[layers]]
  name = "lang#scheme"

[[layers]]
  name = "lang#livescript"

[[layer]]
  name= "lang#julia"

[[custom_plugins]]
name = 'wakatime/vim-wakatime'
enable = true

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#ruby"

[[layers]]
 name = "colorscheme"

