preload = ~/.config/hypr/walls/*.png

# Configurar wallpaper para cada monitor
wallpaper = eDP-1,~/.config/hypr/walls/
wallpaper = DP-5,~/.config/hypr/walls/
wallpaper = HDMI-A-1,~/.config/hypr/walls/

splash = false




#preload = ~/.config/hypr/walls/*.png
#wallpaper = eDP-1,~/.config/hypr/walls/*.png
#splash = false

